### ISSUE TITLE
Vista de inicio de sesión (frontend)

### ISSUE THREAD

**Issue by antsermen** [ISPP-G8/FindMyFun#40]
Creación de la vista correspondiente al inicio de sesión de un usuario. Dicha vista debe contener un formulario sencillo de dos campos (nombre de usuario y contraseña) así como un fondo y color de letra que no moleste la vista del usuario y el título de la página. Se tendrá en consideración favorable que el formulario implementado incluya un ejemplo de datos válidos para iniciar sesión, para que el usuario sepa que debe introducir un nombre de usuario y una contraseña y no cualquier otro dato de su cuenta.

**Comment by jesmarver** [comment]
![Image](https://user-images.githubusercontent.com/39711238/223129335-6b8e42b5-0919-489c-9a6a-39147b4f34e0.png)

**Comment by jesmarver** [comment]
Esta vista se ha completado en la rama de eliminación de evento backend
